### ISSUE TITLE
Support for Monterey

### ISSUE THREAD

**Issue by Brantone** [xfreebird/kcpassword#2]
Looks like issues with using `kcpassword` on macOS 12.3+

Considering Apple has deprecated Python 2.7 and does not come preinstalled on macOS, this poses a problem for the script.

I'm gonna see if have time to carve out a fix, but curious if anyone has something locked 'n loaded.

**Comment by acgourley** [comment]
How would one get this fix via brew?

**Comment by xfreebird** [comment]
@acgourley @milch the brew formula has been updated. 
thanks @milch for your help! much appreciated!

@acgourley to install this keg, run:
```
brew tap xfreebird/utils
brew install kcpassword
```
